---
- name: Install Red Hat Insights client
  hosts: all
  gather_facts: no
  tasks:
    - name: Install the Red Hat Insights client
      yum:
        name: insights-client
        state: latest
      notify:
        - Register Insights

  handlers:
    - name: Register Insights
      command: /bin/insights-client --register
