---
- name: Install Red Hat Insights client
  hosts: app01.young.local app02.young.local app03.young.local db01.young.local db02.young.local idm.young.local 
  gather_facts: no
  tasks:
    - name: Install the Red Hat Insights client
      yum:
        name: insights-client
        state: latest
      notify:
        - Register Insights

  handlers:
    - name: Register Insights
      command: /bin/insights-client --register
